
include:
  - board: akdk_bt1
    shield: swan42_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: swan42_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: settings_reset
